import React from "react";

import MySkillSet from "../../../components/mySkillSet";
import AboutInfo from "../../../components/aboutInfo";
import MouseScroll from "../../../components/mouseScroll";
import ExperienceLine from "../../../components/experienceLine";

export const metadata = {
  title: "About | Secenory",
  description: "Generated by ♥ Secenory",
  icons: {
    icon: "favicon.ico",
  },
};

function AboutPage() {
  return (
    <div className="mb-24 select-none overflow-x-hidden xl:mb-0">
      <AboutInfo />
      <MySkillSet />
      <ExperienceLine />
      <MouseScroll />
    </div>
  );
}

export default AboutPage;
