import React from "react";
import MouseScroll from "../../../components/mouseScroll";
import Projects from "../../../components/projects";

export const metadata = {
  title: "Projects | Emre Ates",
  description: "Generated by ♥ Emre Ates",
  icons: {
    icon: "favicon.ico",
  },
};

function ProjectsPage() {
  return (
    <>
      <Projects />
      <MouseScroll />
    </>
  );
}

export default ProjectsPage;
