import React from "react";
import ContactForm from "../../../components/contactForm";

export const metadata = {
  title: "Contact | Secenory",
  description: "Generated by ♥ Secenory",
  icons: {
    icon: "favicon.ico",
  },
};

function Contact() {
  return <ContactForm />;
}

export default Contact;
