"use client";
import React from "react";
import { OrbitControls, Stage } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";

import Computer from "../../../objects/Computer";
import Atom from "../../../objects/Atom";

export const metadata = {
  title: "Skills | Emre Ates",
  description: "Generated by ♥ Emre Ates",
  icons: {
    icon: "favicon.ico",
  },
};

function SkillsPage() {
  return (
    <div className="flex select-none">
      <div className="flex h-screen w-1/2 flex-col items-center justify-center">
        <h1 className="text-3xl">My Skills</h1>
        <div className="flex flex-col items-center justify-center gap-10">
          <div className="flex gap-x-6">
            <Canvas>
              <Stage environment="city" intensity={0.6}>
                <Atom />
              </Stage>
              <OrbitControls enableZoom={false} autoRotate />
            </Canvas>
          </div>
          <div className="flex gap-x-6">
            <img className="h-20" src="next.png" alt="" />
            <img className="h-20" src="js.png" alt="" />
          </div>
          <div className="flex gap-x-6">
            <img className="h-20" src="html.png" alt="" />
            <img className="h-20" src="css.png" alt="" />
            <img className="h-20" src="sass.png" alt="" />
          </div>
          <div className="flex gap-x-6">
            <img className="h-20" src="bootstrap.png" alt="" />
            <img className="h-20" src="tailwind.png" alt="" />
            <img className="h-20" src="sc.png" alt="" />
            <img className="h-20" src="mui.png" alt="" />
          </div>
          <div className="flex gap-x-6">
            <img className="h-20" src="jquery.png" alt="" />
            <img className="h-20" src="redux.png" alt="" />
            <img className="h-20" src="graphql.png" alt="" />
            <img className="h-20" src="node.png" alt="" />
            <img className="h-20" src="mongo.png" alt="" />
            <img className="h-20" src="postgre.png" alt="" />
          </div>
        </div>
      </div>
      <div className="flex h-screen w-2/5">
        <Canvas>
          <Stage environment="city" intensity={0.6}>
            <Computer />
          </Stage>
          <OrbitControls enableZoom={false} />
        </Canvas>
        {/* <Canvas>
          <Stage environment="city" intensity={0.6}>
            <Atom />
          </Stage>
          <OrbitControls enableZoom={false} autoRotate />
        </Canvas> */}
      </div>
    </div>
  );
}

export default SkillsPage;
